question_data = [
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "There are 2 player roles in Trouble in Terrorist Town.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "In the Fallout: New Vegas add-on Lonesome Road, Ulysses wields a flag pole named The Liberator.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'The game "Jetpack Joyride" was created by "Redbrick Studios".',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In "Super Mario 64", collecting 100 coins on a level will give you a 1-UP.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'The song "Megalovania" by Toby Fox made its third appearence in the 2015 RPG "Undertale".',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In "Sonic Adventure", you are able to transform into Super Sonic at will after completing the main story.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": "The main antagonist in the videogame Saints Row IV is an entity known as The Mastermind.",
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In "Need for Speed: Porsche Unleashed", the player can only drive cars manufactured by Porsche.',
        "correct_answer": "True",
        "incorrect_answers": ["False"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In "Mario Kart 64", Waluigi is a playable character.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
    {
        "type": "boolean",
        "difficulty": "easy",
        "category": "Entertainment: Video Games",
        "question": 'In the game "Subnautica", a "Spadefish" will attack you.',
        "correct_answer": "False",
        "incorrect_answers": ["True"],
    },
]
